#!/usr/bin/env ruby
require 'fileutils'

puts 'Getting needed software to build V4L...'
`sudo apt-get -y install ruby ruby-dev libv4l-dev`

puts 'Building V4L for Ruby...'
FileUtils.rm_f 'video4linux2.so'
`ruby extconf.rb`
`make clean`
`make`
