#!/usr/bin/env ruby
require 'fileutils'

puts 'Getting needed software to build Chipmunk...'
`sudo apt-get -y install ruby1.9.1 ruby1.8-dev ruby1.9.1-dev`

puts 'Building Chipmunk for Ruby 1.8...'
FileUtils.rm_f 'lib/1.8/chipmunk.so'
Dir.chdir('ext/chipmunk') {
	`ruby1.8 extconf.rb`
	`make clean`
	`make`
}

FileUtils.mkdir_p 'lib/1.8'
FileUtils.mv 'ext/chipmunk/chipmunk.so', 'lib/1.8/chipmunk.so'

puts 'Building Chipmunk for Ruby 1.9...'
FileUtils.rm_f 'lib/1.9/chipmunk.so'
Dir.chdir('ext/chipmunk') {
	`ruby1.9.1 extconf.rb`
	`make clean`
	`make`
}
FileUtils.mkdir_p 'lib/1.9'
FileUtils.mv 'ext/chipmunk/chipmunk.so', 'lib/1.9/chipmunk.so'
