#!/usr/bin/env ruby
require 'fileutils'

puts 'Getting needed software to build OpenAL...'
`sudo apt-get -y install ruby1.9.1 ruby1.8-dev ruby1.9.1-dev libopenal1 libopenal-dev libalut-dev libvorbis-dev`

puts 'Building OpenAL for Ruby 1.8...'
`make clean`
`ruby1.8 extconf.rb`
`make`
FileUtils.mkdir_p '1.8'
FileUtils.mv 'openal.so', '1.8/openal.so'

puts 'Building OpenAL for Ruby 1.9...'
`make clean`
`ruby1.9.1 extconf.rb`
`make`
FileUtils.mkdir_p '1.9'
FileUtils.mv 'openal.so', '1.9/openal.so'
