#ifndef RUBY_OPENAL_ALUT_H
#define RUBY_OPENAL_ALUT_H

#ifdef __cplusplus
extern "C" {
#endif

/// module variables
extern VALUE vALUT;

/// ALC module's constants
extern VALUE  vALUT_API_MAJOR_VERSION; // version
extern VALUE  vALUT_API_MINOR_VERSION;
extern VALUE  vALUT_ERROR_NO_ERROR;  // errors
extern VALUE  vALUT_ERROR_OUT_OF_MEMORY;
extern VALUE  vALUT_ERROR_INVALID_ENUM;
extern VALUE  vALUT_ERROR_INVALID_VALUE;
extern VALUE  vALUT_ERROR_INVALID_OPERATION;
extern VALUE  vALUT_ERROR_NO_CURRENT_CONTEXT;
extern VALUE  vALUT_ERROR_AL_ERROR_ON_ENTRY;
extern VALUE  vALUT_ERROR_ALC_ERROR_ON_ENTRY;
extern VALUE  vALUT_ERROR_OPEN_DEVICE;
extern VALUE  vALUT_ERROR_CLOSE_DEVICE;
extern VALUE  vALUT_ERROR_CREATE_CONTEXT;
extern VALUE  vALUT_ERROR_MAKE_CONTEXT_CURRENT;
extern VALUE  vALUT_ERROR_DESTROY_CONTEXT;
extern VALUE  vALUT_ERROR_GEN_BUFFERS;
extern VALUE  vALUT_ERROR_BUFFER_DATA;
extern VALUE  vALUT_ERROR_IO_ERROR;
extern VALUE  vALUT_ERROR_UNSUPPORTED_FILE_TYPE;
extern VALUE  vALUT_ERROR_UNSUPPORTED_FILE_SUBTYPE;
extern VALUE  vALUT_ERROR_CORRUPT_OR_TRUNCATED_DATA;
extern VALUE  vALUT_WAVEFORM_SINE; // waveform
extern VALUE  vALUT_WAVEFORM_SQUARE;
extern VALUE  vALUT_WAVEFORM_SAWTOOTH;
extern VALUE  vALUT_WAVEFORM_WHITENOISE;
extern VALUE  vALUT_WAVEFORM_IMPULSE;
extern VALUE  vALUT_LOADER_BUFFER; // loader
extern VALUE  vALUT_LOADER_MEMORY;


///
extern void setup_module_ALUT();

#ifdef __cplusplus
}
#endif

#endif
