#!/usr/bin/env ruby
require 'fileutils'

puts '### Getting needed software to build ffmpeg video support...'
`sudo apt-get -y install ruby ruby-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libswscale-ffmpeg-dev`

FileUtils.rm_f 'ffmpeg.so'

puts '### Generating makefile...'
`ruby extconf.rb`

puts '### Running makefile...'
`make clean`
`make`
